// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Waveshare-ESP32-S3-Touch-5

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DO0_OUTPUT(lv_event_t * e);
void DO1_OUTPUT(lv_event_t * e);
void listFile(lv_event_t * e);
void toggleBacklight(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
