// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: OBD2_gauge_fusion
#include "waveshare_ch422g.h"
#include "waveshare_sdcard.h"
#include "ui.h"

void DO0_OUTPUT(lv_event_t* e) {
	lv_obj_t* obj = lv_event_get_target(e);  // Get the widget that triggered the event
	bool state = lv_obj_has_state(obj, LV_STATE_CHECKED);
	String txt = String("DO0 ") + (state ? "ON" : "OFF") + "\n";
	lv_textarea_add_text(ui_TextArea1, txt.c_str());
	if (state) {
		DO0_ON;  // your macro or function

	} else {
		DO0_OFF;
	}
}

void DO1_OUTPUT(lv_event_t* e) {
	lv_obj_t* obj = lv_event_get_target(e);  // Get the widget that triggered the event
	bool state = lv_obj_has_state(obj, LV_STATE_CHECKED);
  String txt = String("DO1 ") + (state ? "ON" : "OFF") + "\n";

	lv_textarea_add_text(ui_TextArea1, txt.c_str());
	if (state) {
		DO1_ON;  // your macro or function

	} else {
		DO1_OFF;
	}
}

void listFile(lv_event_t* e) {
	listDir(SD, "/", 0);
}


void toggleBacklight(lv_event_t * e) {
	lv_obj_t* obj = lv_event_get_target(e);  // Get the widget that triggered the event
	bool state = lv_obj_has_state(obj, LV_STATE_CHECKED);
  String txt = String("BL ") + (state ? "ON" : "OFF") + "\n";
	lv_textarea_add_text(ui_TextArea1, txt.c_str());
	if (state) {
		BL_ON;  // your macro or function

	} else {
		BL_OFF;
	}

}
