// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Waveshare-ESP32-S3-Touch-5

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_DO1 = NULL;lv_obj_t *ui_DO2 = NULL;lv_obj_t *ui_DI0 = NULL;lv_obj_t *ui_DI1 = NULL;lv_obj_t *ui_TextArea1 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_backlight = NULL;lv_obj_t *ui_Label3 = NULL;
// event funtions
void ui_event_DO1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      DO0_OUTPUT( e );
}
}

void ui_event_DO2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      DO1_OUTPUT( e );
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      listFile( e );
}
}

void ui_event_backlight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      toggleBacklight( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DO1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_DO1, 100);
lv_obj_set_height( ui_DO1, 50);
lv_obj_set_x( ui_DO1, -340 );
lv_obj_set_y( ui_DO1, -260 );
lv_obj_set_align( ui_DO1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_DO1, lv_color_hex(0xF7665A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DO1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DO2 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_DO2, 100);
lv_obj_set_height( ui_DO2, 50);
lv_obj_set_x( ui_DO2, -340 );
lv_obj_set_y( ui_DO2, -170 );
lv_obj_set_align( ui_DO2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_DO2, lv_color_hex(0xF7665A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DO2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DI0 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_DI0, 100);
lv_obj_set_height( ui_DI0, 50);
lv_obj_set_x( ui_DI0, -340 );
lv_obj_set_y( ui_DI0, -75 );
lv_obj_set_align( ui_DI0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DI0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DI0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DI0, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DI0, lv_color_hex(0x012607), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DI0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DI1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_DI1, 100);
lv_obj_set_height( ui_DI1, 50);
lv_obj_set_x( ui_DI1, -340 );
lv_obj_set_y( ui_DI1, 15 );
lv_obj_set_align( ui_DI1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DI1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DI1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DI1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DI1, lv_color_hex(0x012607), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DI1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 760);
lv_obj_set_height( ui_TextArea1, lv_pct(100));
lv_obj_set_align( ui_TextArea1, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_text(ui_TextArea1,"Waveshare ESP32-S3  Touch LCD 5\"");
lv_textarea_set_placeholder_text(ui_TextArea1,"File List");
lv_obj_set_scrollbar_mode(ui_TextArea1, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_TextArea1, LV_DIR_VER);
lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button2, 176);
lv_obj_set_height( ui_Button2, 73);
lv_obj_set_x( ui_Button2, -384 );
lv_obj_set_y( ui_Button2, 238 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFA08FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"SD CARD");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -448 );
lv_obj_set_y( ui_Label2, -216 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"DO0\n\n\nDO1");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFD0505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -454 );
lv_obj_set_y( ui_Label4, -30 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"DI0\n\n\nDI1");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x0408F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backlight = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_backlight, 100);
lv_obj_set_height( ui_backlight, 50);
lv_obj_set_x( ui_backlight, -340 );
lv_obj_set_y( ui_backlight, 114 );
lv_obj_set_align( ui_backlight, LV_ALIGN_CENTER );
lv_obj_add_state( ui_backlight, LV_STATE_CHECKED );     /// States
lv_obj_set_style_bg_color(ui_backlight, lv_color_hex(0x003DF9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -454 );
lv_obj_set_y( ui_Label3, 113 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"BL");

lv_obj_add_event_cb(ui_DO1, ui_event_DO1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DO2, ui_event_DO2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_backlight, ui_event_backlight, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_DO1= NULL;
ui_DO2= NULL;
ui_DI0= NULL;
ui_DI1= NULL;
ui_TextArea1= NULL;
ui_Button2= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Label4= NULL;
ui_backlight= NULL;
ui_Label3= NULL;

}
