// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Waveshare-ESP32-S3-Touch-5

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern void ui_event_DO1( lv_event_t * e);
extern lv_obj_t *ui_DO1;
extern void ui_event_DO2( lv_event_t * e);
extern lv_obj_t *ui_DO2;
extern lv_obj_t *ui_DI0;
extern lv_obj_t *ui_DI1;
extern lv_obj_t *ui_TextArea1;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label4;
extern void ui_event_backlight( lv_event_t * e);
extern lv_obj_t *ui_backlight;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

